# numpy in python

In [2]:
import numpy as np

Adventages of numpy array over python list:
- consumes less memory
- fast as compared to python list
- Convinient to use

In [5]:
%timeit np.array([1,2,3,4])

890 ns ± 17.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
%timeit a = [1,2,3,4]

74.5 ns ± 2.75 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [8]:
a = list(range(1000000))

%timeit [x * 2 for x in a]

92.9 ms ± 2.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
import numpy as np

a = np.arange(1000000)

%timeit a * 2

4.16 ms ± 329 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Creating numpy array

In [10]:
x = [1,2,3,4] # list
y = np.array(x)

In [11]:
y

array([1, 2, 3, 4])

In [12]:
type(y)

numpy.ndarray

# Built-in Methods se Arrays

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [17]:
np.linspace(0, 10, 5) # Matlab 0 se 10 tak 5 equal numbers.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.empty(3)

array([0., 0., 0.])

# Random Arrays

In [21]:
np.random.rand(5) # 0 se 1 ke beech random numbers.

array([0.9564002 , 0.79035909, 0.22304944, 0.10083964, 0.81438437])

In [23]:
np.random.randn(5) # generate a random value close to zero

array([ 0.41360876,  0.56935548,  0.40462752, -1.49024983,  1.68813101])

In [25]:
np.random.ranf(5) # 0 se 1 k darmiyan ho gi magar floating point ma ho gi

array([0.22859553, 0.353881  , 0.8315888 , 0.35802243, 0.46243827])

In [28]:
np.random.randint(5,10,5) # (min,max,no. in an array)

array([6, 5, 9, 6, 6], dtype=int32)

# Dimensions in Numpy Array

# 1D Array

In [35]:
x = [1,2,3,4] # list
y = np.array(x)
print(y.ndim)
y

1


array([1, 2, 3, 4])

# 2D Array

In [36]:
x = [[1,2,3,4],[1,2,3,4]] # list
z = np.array(x)
print(z.ndim)
z

2


array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

# 3D Array

In [39]:
x = [[[1,2,3,4],[1,2,3,4],[1,2,3,4]]] # list
w = np.array(x)
print(w.ndim)
w

3


array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

# nD Array

In [3]:
r = [[[1,2,3,4],[1,2,3,4],[1,2,3,4]]] # list
q = np.array(r,ndmin=10 )
print(q.ndim)
q

10


array([[[[[[[[[[1, 2, 3, 4],
               [1, 2, 3, 4],
               [1, 2, 3, 4]]]]]]]]]])

In [6]:
t = [1,2,3,4]
arr = np.array(t,ndmin=3)
print(arr.ndim)
arr

3


array([[[1, 2, 3, 4]]])