# Type Casting in NumPy

In [1]:
import numpy as np

arr = np.array([1, 2, 3])

print(arr.dtype)

int64


In [2]:
arr = arr.astype(float)

print(arr)
print(arr.dtype)

[1. 2. 3.]
float64


In [3]:
arr = np.array([1.5, 2.9, 3.2])

arr = arr.astype(int)

print(arr)

[1 2 3]


# Arithmetic Operations on NumPy Arrays

In [4]:
a = np.array([10,20,30])
b = np.array([1,2,3])
a+b

array([11, 22, 33])

In [5]:
a-b

array([ 9, 18, 27])

In [6]:
a*b

array([10, 40, 90])

In [7]:
a/b

array([10., 10., 10.])

In [8]:
a**2

array([100, 400, 900])

### Scalar operations (Broadcasting use hota hai)

In [9]:
a + 5

array([15, 25, 35])

# Universal Functions (ufuncs)

In [13]:
arr = np.array([1,4,9,16])

In [11]:
np.sqrt(arr)

array([1., 2., 3., 4.])

In [14]:
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [15]:
np.sin(arr)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332])

In [16]:
np.abs(np.array([-1,-2,3]))

array([1, 2, 3])

# Practice (Very Important)

- Integer array ko float me convert karo

- Do arrays ka multiplication karo

- Array ka square nikalo

- sqrt apply karo

- Array me sin apply karo