# Data Loading & Saving in NumPy

### Save array (.npy file)

In [1]:
import numpy as np 
arr = np.array([1,2,3,4])
np.save("data.npy",arr)

### Load array

In [2]:
arr = np.load("data.npy")

In [3]:
print(arr)

[1 2 3 4]


### Multiple arrays save (.npz) and load

In [4]:
a = np.array([1,2])
b = np.array([3,4])
np.savez("Multiple.npz",a=a,b=b)

In [6]:
data = np.load("Multiple.npz")

print(data["a"])
print(data["b"])

[1 2]
[3 4]


# NumPy Indexing and Selection

In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.ndim)
arr

2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(arr[1,2]) # Single element access

6


In [15]:
print(arr[1]) # arr[1] -> complete row

[4 5 6]


In [3]:
arr[:,1] #Complete column

array([2, 5, 8])

In [2]:
arr[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr[0:2, 1:3] # Slicing, arr[row_start:row_end, col_start:col_end]

array([[2, 3],
       [5, 6]])

In [3]:
arr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

# Logical Selection (Filtering)

In [18]:
arr = np.array([10,20,30,40])

arr > 20

array([False, False,  True,  True])

In [19]:
arr[arr > 20]

array([30, 40])

In [20]:
arr[arr % 20 == 0]

array([20, 40])

# Broadcasting

In [21]:
arr = np.array([1,2,3])

arr + 5

array([6, 7, 8])

In [22]:
# 2D Broadcasting
arr = np.array([[1,2,3],
                [4,5,6]])

arr + np.array([10,20,30])

array([[11, 22, 33],
       [14, 25, 36]])